const app=document.getElementById('app');const A='assets/';
const sheets={front:'vowel_mouths_01_front_central.png',back:'vowel_mouths_02_back.png',diph:'vowel_mouths_03_diphthongs.png',lips:'mouth_atlas_01_lips.png',tongue:'mouth_atlas_02_tongue_front.png',fric:'mouth_atlas_03_fricatives.png',rear:'mouth_atlas_04_back_and_glottal.png'};
const records=[...vowels.map(x=>({kind:'母音',x})),...consonants.map(x=>({kind:'子音',x}))];const recordMap=new Map(records.map(o=>[o.x[0],o]));
let sideManifest=window.__SIDE_MANIFEST__||{},currentClip=null,slow=false,speechToken=0,voices=[],currentSound='i',step=0;
if(!window.__SIDE_MANIFEST__)fetch('side-manifest.json').then(r=>r.json()).then(m=>{sideManifest=m;if(location.hash.startsWith('#/sound/'))route()}).catch(()=>{});
function enVoice(){const list=voices.filter(v=>v.lang.toLowerCase().startsWith('en-us'));return list.find(v=>/natural|premium|enhanced/i.test(v.name))||list[0]}
function loadVoices(){if('speechSynthesis'in window)voices=speechSynthesis.getVoices()}loadVoices();if('speechSynthesis'in window)speechSynthesis.addEventListener('voiceschanged',loadVoices);
function say(text,rate,onEnd,token){const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;u.pitch=1;if(enVoice())u.voice=enVoice();u.onend=()=>{if(token===speechToken&&onEnd)onEnd()};u.onerror=()=>{if(token===speechToken)setFeedback('播放中斷，請再點一次。')};speechSynthesis.speak(u)}
function setFeedback(t){const el=document.getElementById('audioStatus');if(el)el.textContent=t}
function halt(){if(currentClip){currentClip.pause();currentClip.currentTime=0;currentClip=null}document.querySelector('.soundButton.isPlaying')?.classList.remove('isPlaying');if('speechSynthesis'in window)speechSynthesis.cancel()}
function playWord(word){if(!('speechSynthesis'in window)){setFeedback('此瀏覽器不支援例字語音播放。');return}const token=++speechToken;halt();setFeedback(`播放例字：${word}`);say(word,slow?.7:.92,()=>setFeedback(''),token)}
function plainPhrase(phrase){return phrase.replace(/[\[\]]/g,'')}
function markedPhrase(phrase){const escape=t=>t.replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));return escape(phrase).replace(/\[([A-Za-z]+)\]/g,'<span class="targetLetters">$1</span>')}
function playPhrase(sym,index){if(!('speechSynthesis'in window)){setFeedback('此瀏覽器不支援語音播放。');return}const phrase=practicePhrases[sym]?.[index];if(!phrase)return;const token=++speechToken;halt();setFeedback('播放短句中…');say(plainPhrase(phrase),1.04,()=>setFeedback(''),token)}
function playSound(sym){const source=phonemeManifest[sym];const status=document.getElementById('soundStatus');if(!source){if(status)status.textContent='這個音標暫時無法播放。';return}const token=++speechToken;halt();const button=document.querySelector('.soundButton[data-sym="'+sym+'"]');const clip=new Audio(source);currentClip=clip;button?.classList.add('isPlaying');if(status)status.textContent='播放音標 '+sym;const done=()=>{if(token!==speechToken)return;currentClip=null;button?.classList.remove('isPlaying');if(status)status.textContent=''};clip.onended=done;clip.onerror=()=>{done();if(status)status.textContent='音檔暫時無法播放，請再點一次。'};clip.play().catch(()=>{done();if(status)status.textContent='音檔暫時無法播放，請再點一次。'})}
function playPair(sym){const item=recordMap.get(sym);if(!item)return;const token=++speechToken;halt();const word=item.x[1];setFeedback('獨立音素 → '+word);const speakExample=()=>{if(token!==speechToken)return;if('speechSynthesis'in window)say(word,slow?.7:.92,()=>setFeedback(''),token);else setFeedback('已播放單音；此瀏覽器不支援例字語音。')};const source=phonemeManifest[sym];if(source){const clip=new Audio(source);currentClip=clip;clip.playbackRate=slow?.82:1;clip.onended=()=>{currentClip=null;speakExample()};clip.onerror=()=>{currentClip=null;fallback()};clip.play().catch(()=>{currentClip=null;fallback()})}else fallback();function fallback(){if(token!==speechToken)return;if(!('speechSynthesis'in window)){setFeedback('此瀏覽器無法播放音訊。');return}setFeedback('合成單音提示 → '+word);say(cueText[sym],slow?.68:.84,speakExample,token)}}
function path(sym,level='sound'){return '#/'+level+'/'+encodeURIComponent(sym)}
function breadcrumb(sym,level){return `<div class="crumb"><a href="#/chart">音標總表</a><span>›</span>${level==='practice'?`<a href="${path(sym)}">/${sym}/ 圖解</a><span>›</span><span>練習</span>`:`<span>/${sym}/ 圖解</span>`}</div>`}
function soundTile(o){const sym=o.x[0];return `<a class="tile" href="${path(sym)}" aria-label="查看音標 ${sym} 的發音圖解"><span class="tileSymbol">${sym}</span></a>`}
function renderChart(){document.title='KK 音標互動學習';document.getElementById('navTrail').textContent='';app.innerHTML=`<div class="chartPage"><div class="pageIntro"><h1>KK 音標總表</h1><p>點選音標，查看口型、舌位和發音解說。</p></div><section class="section vowelSection"><div class="sectionHead"><h2>母音</h2><span class="muted">17 個</span></div><div class="grid">${records.filter(o=>o.kind==='母音').map(soundTile).join('')}</div></section><section class="section consonantSection"><div class="sectionHead"><h2>子音</h2><span class="muted">24 個</span></div><div class="grid">${records.filter(o=>o.kind==='子音').map(soundTile).join('')}</div></section></div>`}
function frontSpec(x){const [sym,word,place,tip,key,idx]=x;if(key.startsWith('rhotic_'))return {src:A+key,rects:[[0,172,1536,852]]};if(key==='front'||key==='back')return {src:A+sheets[key],rects:[[idx%3*512,165+Math.floor(idx/3)*512,512,435]]};if(key==='diph')return {src:A+sheets[key],rects:[[0,165+idx*341,768,265],[768,165+idx*341,768,265]]};return {src:A+sheets[key],rects:[[idx%3*557,101+Math.floor(idx/3)*467,557,360]]}}
function renderFront(x){const box=document.getElementById('frontArt');if(!box)return;const cfg=frontSpec(x);const pair=cfg.rects.length===2;box.classList.toggle('hasPair',pair);box.innerHTML='<canvas role="img"></canvas>';const c=box.querySelector('canvas');c.width=pair?800:640;c.height=pair?630:400;c.setAttribute('aria-label',`/${x[0]}/ 的正面口型${pair?'，先看上方起點再看下方終點':''}`);const im=new Image();im.onload=()=>{const ctx=c.getContext('2d');ctx.fillStyle='#061b31';ctx.fillRect(0,0,c.width,c.height);cfg.rects.forEach(([sx,sy,sw,sh],i)=>{const maxW=pair?768:620,maxH=pair?270:380;const scale=Math.min(maxW/sw,maxH/sh);const dw=sw*scale,dh=sh*scale;const yBase=pair?(i===0?12:348):10;ctx.drawImage(im,sx,sy,sw,sh,(c.width-dw)/2,yBase+(maxH-dh)/2,dw,dh)});if(pair){ctx.fillStyle='#72dce9';ctx.font='bold 38px sans-serif';ctx.textAlign='center';ctx.fillText('↓',400,333)}};im.onerror=()=>box.textContent='正面圖暫時無法載入';im.src=cfg.src}
const pairedSides=new Set(['aɪ','aʊ','ɔɪ','p','b','t','d','k','g','tʃ','dʒ']);
const plainSides=new Set(['i','ɪ','e','ɛ','æ','ə','ʌ','u','ʊ','o','ɔ','ɑ','ɚ','ɝ','w','j','r']);
function renderSide(sym,src){const box=document.getElementById('sideArt');if(!box)return;if(!src){box.textContent='側面圖載入中…';return}const pair=pairedSides.has(sym);box.classList.toggle('hasPair',pair);box.innerHTML='<canvas role="img"></canvas>';const c=box.querySelector('canvas');c.width=1200;c.height=pair?590:676;c.setAttribute('aria-label',`/${sym}/ 的側面舌位示意圖${pair?'，兩個姿勢完整呈現':''}`);const im=new Image();im.onload=()=>{const ctx=c.getContext('2d');ctx.fillStyle='#061b31';ctx.fillRect(0,0,c.width,c.height);if(pair){ctx.drawImage(im,0,86,1200,590,0,0,1200,590)}else if(plainSides.has(sym)){ctx.drawImage(im,0,0,930,676,135,0,930,676)}else{ctx.drawImage(im,0,0,1200,676);ctx.fillStyle='#05233e';ctx.fillRect(950,0,250,172)}};im.onerror=()=>box.textContent='側面圖暫時無法載入';im.src=src}
function positionBlock(sym){const pos=positionWords[sym];if(!pos)return '';const labels=['字首','字中','字尾'];return `<section class="card positionSection"><h2>子音在單字中的位置</h2><p class="muted">點例字聽發音，留意同一個音在不同位置的變化。</p><div class="positions">${pos.map((w,i)=>w?`<button class="positionButton" type="button" data-action="word" data-word="${w}"><span class="positionLabel">${labels[i]}</span>${w}　▶</button>`:`<div class="noPosition"><span class="positionLabel">${labels[i]}</span>英語中通常無此位置的獨立 /${sym}/</div>`).join('')}</div></section>`}
function renderDetail(sym){const o=recordMap.get(sym);if(!o){location.hash='#/chart';return}currentSound=sym;const x=o.x;document.title=`/${sym}/ ${x[1]}｜KK 音標圖解`;document.getElementById('navTrail').textContent='› '+sym;const side=sideManifest[sym];app.innerHTML=`${breadcrumb(sym,'sound')}<h1 class="soundTitle"><button class="soundButton ${o.kind==='母音'?'vowel':'consonant'}" type="button" data-action="sound" data-sym="${sym}" aria-label="播放音標 ${sym} 的發音">${sym}</button></h1><p class="srOnly" id="soundStatus" role="status"></p><div class="detailLayout"><div class="visualGrid"><article class="visualCard"><h2>正面口型</h2><div class="visualFrame" id="frontArt"></div><p>觀察嘴唇與下顎；舌頭內部位置以側面圖為準。</p></article><article class="visualCard"><h2>側面舌位與氣流</h2><div class="visualFrame" id="sideArt"></div><p>側面圖為示意姿勢，實際發音會因個人與語境略有不同。</p></article></div><article class="card explainer"><h2>發音方式與舌位</h2><p>${x[2]}</p><h2>發音要點</h2><p>${x[3]}</p><p class="note">${o.kind==='子音'?'比較聲帶是否振動、接觸點及氣流釋放。':'比較舌位高低、前後與唇形變化。'}</p></article></div><section class="card wordSection" aria-label="示範例字"><div class="words">${practiceWords[sym].map(w=>`<button class="wordButton" type="button" data-action="word" data-word="${w}" aria-label="播放 ${w}，KK 音標 ${wordKK[w]}"><span class="wordLabel">${w}</span><span class="wordIPA">/${wordKK[w]}/</span><span class="wordPlay" aria-hidden="true">▶</span></button>`).join('')}</div><p class="feedback" id="audioStatus" role="status"></p></section>${o.kind==='子音'?positionBlock(sym):''}<div class="detailBottom"><a class="btn primary" href="${path(sym,'practice')}">進階練習 →</a></div>`;renderFront(x);renderSide(sym,side)}
function renderPractice(sym){
 const o=recordMap.get(sym);if(!o){location.hash='#/chart';return}
 if(currentSound!==sym){step=0;currentSound=sym}
 const phrases=practicePhrases[sym],translations=phraseTranslations[sym];step=Math.min(Math.max(0,step),phrases.length-1);
 document.title=`/${sym}/ 短句練習｜KK 音標互動學習`;
 document.getElementById('navTrail').textContent='› '+sym+' 練習';
 app.innerHTML=`<div class="practiceShell">${breadcrumb(sym,'practice')}<div class="practiceTop"><div class="pageIntro"><div class="eyebrow">第三層 · 日常短句練習</div><h1>/${sym}/　20 句練習</h1><p>紅色字母標示目標音。點選句子或中央播放鍵，聽自然語速的美式英語。</p></div></div><section class="card drill"><div class="drillNo">${step+1} / ${phrases.length}</div><div class="drillPhrase" lang="en">${markedPhrase(phrases[step])}</div><div class="drillTranslation" lang="zh-Hant">${translations[step]}</div><div class="drillControls"><button class="drillSkip" type="button" data-action="prev" ${step===0?'disabled':''}>上一句</button><button class="playTriangle" type="button" data-action="phrase" aria-label="播放這一句"></button><button class="drillSkip" type="button" data-action="next" ${step===phrases.length-1?'disabled':''}>下一句</button></div><p class="feedback" id="audioStatus" role="status"></p></section><section class="card phraseSection"><h2>20 句日常練習</h2><div class="phraseList">${phrases.map((phrase,i)=>`<button type="button" class="phraseItem ${i===step?'selected':''}" data-action="select" data-index="${i}" aria-label="播放第 ${i+1} 句：${plainPhrase(phrase).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}；${translations[i]}"><span class="phraseNumber">${String(i+1).padStart(2,'0')}</span><span class="phraseText"><span class="phraseEnglish" lang="en">${markedPhrase(phrase)}</span><span class="phraseTranslation" lang="zh-Hant">${translations[i]}</span></span></button>`).join('')}</div></section>${o.kind==='子音'?`<section class="card drillContext"><h2>換個位置聽 /${sym}/</h2><p>在<a href="${path(sym)}">圖解頁</a>可比較字首、字中與字尾的例字。</p></section>`:''}</div>`
}
function route(){const raw=location.hash.replace(/^#\/?/,'').split('/');let level=raw[0]||'chart',sym='';try{sym=decodeURIComponent(raw[1]||'')}catch{}if(level==='sound')renderDetail(sym);else if(level==='practice')renderPractice(sym);else renderChart();window.scrollTo({top:0,behavior:'instant'})}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(action==='sound')playSound(b.dataset.sym);if(action==='detail')location.hash=path(b.dataset.sym);if(action==='word')playWord(b.dataset.word);if(action==='phrase')playPhrase(currentSound,step);if(action==='select'){step=Number(b.dataset.index);renderPractice(currentSound);playPhrase(currentSound,step)}if(action==='prev'&&step>0){step--;renderPractice(currentSound);playPhrase(currentSound,step)}if(action==='next'&&step<practicePhrases[currentSound].length-1){step++;renderPractice(currentSound);playPhrase(currentSound,step)}});
window.addEventListener('hashchange',()=>{speechToken++;halt();route()});route();
